### ISSUE TITLE
MeetUp Change Efforts

### ISSUE THREAD

**Issue by luccacabra** [Austin-Devops/austin-devops#1]
This issue is meant to serve as the main tracking mechanism for all work on the Austin DevOps MeetUp re-org/enhancement/whatever-buzzword-floats-your-boat effort.

*I've just jotted down some thoughts/structure that were top of mind. I'll continue to enhance this list/make sub-issues, but please everyone feel free to contribute to the issue in the mean time!*
____
## Chat Client
In order to reduce noise, increase discoverability, support a SIG structure, and encourage more community interactions, we want to switch to a chat solution that has a [organization/channel](https://get.slack.help/hc/en-us/articles/217626298-Getting-started-for-workspace-creators#3.-workspace-setup-and-organization) structure.
### Requirements
* Free
* Unlimited Chat History
    * How concerned are we with unlimited message history?
    * Why are we concerned with unlimited message history?
        * Can we address these concerns through another means? (archiving message history periodically, etc)
* Ability for *all* users to create new channels
### Tasks
1. - [ ] [Define list of **must** haves and **nice to** haves for a chat client](#6) <img src="https://img.shields.io/badge/-In%20Progress-red.svg?style=flat&colorA=555555&colorB=618685"/>
2. - [ ] investigate chat client technologies
    * - [ ] [chanty](https://www.chanty.com/)
        * Beta
        * Unlimited message history for free
    * - [ ] [rocket.chat](https://rocket.chat/)
        * Self Hosted
        * Free unlimited everything (whatever your hosting solution can support)
    * - [ ] [ryver](https://ryver.com)
        * free tier includes unlimited members/messages/storage
        * integrations use requires paid plan
    * - [ ] [slack](https://slack.com)
        * 10k message history for free
    * - [ ] [freenode](https://freenode.net/)
3. - [ ] setup the chat client
4. - [ ] surface chat client via website/meetup
5. - [ ] publicize chat client to members
6. - [ ] add `/remind` action to `#atxdevops` with link to new chat client

### Tasks
- [ ] [Decide on Hosting Solution](#5) <img src="https://img.shields.io/badge/-In%20Progress-red.svg?style=flat&colorA=555555&colorB=618685"/>
- [ ] Landing page
- [ ] SIGs
- [ ] CoC
- [ ] Organizers
- [ ] Formal Contact Forms
    - [ ] Request to Sponsor
    - [ ] Request to Speak
    - [ ] Contact Organizers

### Tasks

**Comment by jjasghar** [comment]
My vote will always be for freenode, but i understand that's a limiting our community.

I would like to say that as we figure out what we want to do, we can use the `/remind` action for a "weekly/every other week" announcement in the #atxdevops channel to announce **where** we have moved.

**Comment by jjasghar** [comment]
We should verify https://github.com/Austin-Devops/austin-devops/issues/5 as part of this overarching plan.

**Comment by luccacabra** [comment]
@jjasghar 👍 to the `/remind` action in `#atxdevops`. Would also be nice to implement a similar feature in the new client that acts as a reminder for upcoming meetups.

**Comment by moutons** [comment]
going to close this since it's been dormant since 2018
